// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuWjpuZl0-rfdz3mCjVrGF7M5aWHZs7Vw',
    appId: '1:811987506575:web:03ad4f5904a9aaec37e7fa',
    messagingSenderId: '811987506575',
    projectId: 'unihub-37112',
    authDomain: 'unihub-37112.firebaseapp.com',
    storageBucket: 'unihub-37112.appspot.com',
    measurementId: 'G-STHFBNEEZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2Zzfh0fT3Wm6sviQGYLPEtDPEckTqWOQ',
    appId: '1:811987506575:android:9e1488d4fdfab1ff37e7fa',
    messagingSenderId: '811987506575',
    projectId: 'unihub-37112',
    storageBucket: 'unihub-37112.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq5RyY_H0XD09u4byjkfFZyr4wdPOPleU',
    appId: '1:811987506575:ios:13803f2b5d497da737e7fa',
    messagingSenderId: '811987506575',
    projectId: 'unihub-37112',
    storageBucket: 'unihub-37112.appspot.com',
    iosClientId: '811987506575-a1aosp24odlukic22g6bs3dvntalo45b.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectUnihub',
  );
}
